### ISSUE TITLE
I want to add Sorting Algorithm in C++ Language please assign me 

### ISSUE THREAD

**Issue by iamakhileshmishra** [shikaruki/Hactoberfest2021#198]

**Comment by Rohit-R2000** [comment]
Sir i want to contribute in your repository , I can add quicksort algorithm as it works on divide and conquer approach so it is most efficient sorting algo . So please can u assign this to me

**Comment by iamakhileshmishra** [comment]
This repo has been excluded from hacktoberfest do not contribute on this
